
from game_math import GameMath
import json

def verify_clouds():
    gm = GameMath()
    result = gm.generate_round_result(100)
    spawn_data = result['spawn_data']
    clouds = spawn_data['clouds']
    
    print(f"Total clouds: {len(clouds)}")
    
    # Check for non-random clouds (generated by path logic)
    path_clouds = [c for c in clouds if not c.get('is_cosmetic')]
    cosmetic_clouds = [c for c in clouds if c.get('is_cosmetic')]
    
    print(f"Path clouds: {len(path_clouds)}")
    print(f"Cosmetic clouds: {len(cosmetic_clouds)}")
    
    print("\nSample Path Clouds:")
    for i, c in enumerate(path_clouds[:10]):
        print(f"Cloud {i}: x={c['x']}, y={c['y']}, type={c['type']}")
        
    print("\nSample Cosmetic Clouds:")
    for i, c in enumerate(cosmetic_clouds[:5]):
        print(f"Cloud {i}: x={c['x']}, y={c['y']}, type={c['type']}")

if __name__ == "__main__":
    verify_clouds()
